### ISSUE TITLE
Understanding train.prototxt

### ISSUE THREAD

**Issue by opraveen** [sjuvekar/Kaggle-Whales-Caffe#1]
Hi, I am going through the neural network for each of the four points. The last three layers in point1_x_train.prototxt -

DRelu17 (ReLU deconv)
ip1 (Fully connected)
final (Sigmoid)
loss

Since the label here is a x_point in space (float), why do we need 'final-sigmoid' layer? Isn't output of "ip1" a better fit (for prediction) in this case

692 layer {
693   name: "drelu17"
694   type: "ReLU"
695   bottom: "deconv17"
696   top: "deconv17"
697 } 
698 layer {
699   name: "ip1"
700   type: "InnerProduct"
701   bottom: "deconv17"
702   top: "ip1"
703   inner_product_param {
704     num_output: 1
705     weight_filler {
706       type: "gaussian"
707       std: 0.1
708     }
709   }  
710 }  
711 layer {
712   name: "final"
713   type: "Sigmoid"
714   bottom: "ip1"
715   top: "final"
716 } 
717 layer {
718   name: "loss"
719   type: "EuclideanLoss"
720   bottom: "final"
721   bottom: "label"
722   top: "loss"
723 }

**Comment by sjuvekar** [comment]
Hmm, that looks more accurate. Let me make changes and commit. Better, feel free to send a Pull Request. I couldn't find time to work more and train anything beyond a few iters yet.

**Comment by opraveen** [comment]
Pull request @ https://github.com/sjuvekar/Kaggle-Whales-Caffe/pull/2
